import type { MutableGameState } from "../src/game/types";
import { v3 } from "../src/game/utils/math";

export function makeTestState(): MutableGameState {
  return {
    mode: "build",
    time: 0,
    resources: { gold: 100, mana: 60, essence: 0 },
    hero: {
      id: "hero",
      position: v3(),
      velocity: v3(),
      facing: v3(1, 0, 0),
      stats: {
        health: 100,
        maxHealth: 100,
        attackDamage: 12,
        attackSpeed: 1,
        critChance: 0.1,
        moveSpeed: 5,
      },
      loadout: {
        weapon: "crossbow",
        ability1: "explosive-rune",
        ability2: "freezing-pulse",
      },
      alive: true,
      respawnTimer: 0,
      attackCooldown: 0,
      abilityCooldowns: {
        dash: 0,
        "explosive-rune": 0,
        "freezing-pulse": 0,
        "healing-beacon": 0,
        "overcharge-aura": 0,
      },
      invulnerabilityTimer: 0,
      jumpActive: false,
      jumpElapsed: 0,
      jumpDuration: 0.42,
      jumpPeakHeight: 1.05,
    },
    enemies: [],
    towers: [],
    traps: [],
    projectiles: [],
    floatingTexts: [],
    placementPreview: {
      position: v3(),
      canPlace: false,
      blockReason: null,
      sellTarget: null,
    },
    selectedBuildType: "ballista",
    selectedTargetId: null,
    currentBiomeIndex: 0,
    enemyRoutePreview: [],
    wave: {
      active: false,
      biomeIndex: 0,
      waveIndexInBiome: 0,
      globalWaveNumber: 1,
      bossSpawned: false,
      spawnQueue: [],
      enemiesRemainingEstimate: 0,
      clearDelay: 0,
    },
    availableUpgrades: [],
    ownedUpgradeIds: new Set(),
    baseCoreHealth: 200,
    baseCoreMaxHealth: 200,
    minimapDirty: false,
    settings: {
      difficultyTier: 1,
      quality: "medium",
      masterVolume: 0.7,
    },
    modifiers: {
      heroDamageMultiplier: 1,
      heroAttackSpeedMultiplier: 1,
      heroMoveSpeedMultiplier: 1,
      towerDamageMultiplier: 1,
      towerRangeMultiplier: 1,
      towerAttackSpeedMultiplier: 1,
      trapDamageMultiplier: 1,
      freezeDurationMultiplier: 0,
      slowStrengthMultiplier: 0,
      shockVulnerabilityBonus: 0,
      poisonedAttacks: false,
      shockExplosionOnDeath: false,
      firePoolsOnBombard: false,
      overchargePulseChance: 0,
      economyGoldMultiplier: 1,
      economyManaOnTrapTrigger: 0,
      towerCostMultiplier: 1,
      trapCostMultiplier: 1,
      allSlowEffectsStack: false,
    },
    runStats: {
      kills: 0,
      wavesCleared: 0,
      bossesDefeated: 0,
      goldSpent: 0,
      damageDealt: 0,
    },
  };
}
